# Generated by Django 3.2 on 2021-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opponent_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id'),
        ),
    ]
