# Generated by Django 3.2 on 2021-06-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_opponent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
