# Generated by Django 3.2 on 2021-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(1, '等待对手'), (2, '游戏开始'), (3, '游戏结束')], default=1),
        ),
    ]
