# Generated by Django 3.2 on 2021-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=92),
        ),
    ]
